(()=>{'use strict';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ledger=[];
const stateRank={A3:3,A2:2,A1:1,A0:0};
const now=()=>new Date().toISOString();
function addLedger(evidence,decision,authority,burden){ledger.push({timestamp:now(),evidence,decision,authority,burden});renderLedger()}
function renderLedger(){const rows=$('ledgerRows');rows.innerHTML=ledger.map(x=>`<tr><td>${new Date(x.timestamp).toLocaleTimeString()}</td><td>${x.evidence}</td><td>${x.decision}</td><td><strong>${x.authority}</strong></td><td>${x.burden}</td></tr>`).join('')||'<tr><td colspan="5">No decision records yet. Generate a policy, replay a sequence, compare architectures, or inspect a command.</td></tr>'}
function setHero(authority,budget,validity,dwell){$('heroState').textContent=authority;$('heroBudget').textContent=budget.toFixed(2);$('heroValidity').textContent=validity;$('heroBurden').textContent=`${dwell} samples`}
function missionAuthority(){const f=+$('fcoiPressure').value,s=+$('sensorHealth').value,p=$('provenanceGood').checked,w=$('witnessIndependent').checked,g=$('groundLink').checked,max=$('maxAuthority').value;let a=!p||!w||s<.35||f>.82?'A0':s<.55||f>.62?'A1':!g||s<.72||f>.42?'A2':'A3';return stateRank[a]>stateRank[max]?max:a}
function generatePolicy(){const craft=$('craft').value,phase=$('phase').value,dwell=+$('recoveryDwell').value,f=+$('fcoiPressure').value,s=+$('sensorHealth').value,p=$('provenanceGood').checked,w=$('witnessIndependent').checked,g=$('groundLink').checked,a=missionAuthority(),invariants=[...document.querySelectorAll('input[name="invariant"]:checked')].map(x=>x.value);const valid=p&&w&&s>=.35;const budget=valid?clamp(1-Math.max(f,1-s)*1.08,0,1):0;$('policyName').textContent=`${craft} · ${phase}`;$('policyAuthority').textContent=a;$('policyPilot').textContent=a==='A3'?'May propose bounded mission actions; no direct actuator path.':a==='A2'?'May propose only inside the restricted phase envelope.':a==='A1'?'Advisory output only; no actuation request may be accepted.':'Removed from the actuation path; reasoning may be logged but creates no permission.';$('policyWatchdog').textContent=`Rejects proposals outside the ${phase.toLowerCase()} envelope, including stale, unauthenticated, or physically invalid commands.`;$('policyVigil').textContent=`FCOI=${f.toFixed(2)}, sensor health=${s.toFixed(2)}, provenance=${p?'valid':'invalid'}, witness=${w?'independent':'not independent'}. Evidence may only reduce permission.`;$('policyAnchor').textContent=`Preserves ${invariants.length?invariants.join(', '):'the minimum declared survivable action set'}.`;$('policyRecovery').textContent=`Sequential promotion after ${dwell} healthy samples with fresh independent evidence${g?' and authenticated ground contact available for diagnostics.':'; ground link remains unavailable and cannot be treated as an override.'}`;setHero(a,budget,valid?'VALID':'UNKNOWN / INVALID',dwell);addLedger(`Mission profile: ${phase}; FCOI ${f.toFixed(2)}; sensor ${s.toFixed(2)}; provenance ${p?'valid':'invalid'}`,`Generated illustrative policy and selected ${a}`,a,`Restore sequentially after ${dwell} healthy samples`)}
$('missionForm').onsubmit=e=>{e.preventDefault();generatePolicy()};[['sensorHealth','sensorOut'],['fcoiPressure','fcoiOut']].forEach(([i,o])=>$(i).oninput=e=>$(o).textContent=(+e.target.value).toFixed(2));
const faults={sensor:{name:'Correlated sensor bias',mono:['Strategic controller trusts the biased estimate.','Unsafe correction reaches actuation.'],layer:['Primary and safety channel share the same sensor model.','Both accept the biased estimate as independent confirmation.'],cerb:['Vigil sees agreement but structural FCOI exposes shared roots.','Authority contracts before the maneuver can bypass Watchdog.']},command:{name:'Stale authenticated command',mono:['Valid signature is mistaken for current intent.','Command executes after its operational context has expired.'],layer:['Both layers accept the same stale command bus.','Nominal redundancy repeats the same mistake.'],cerb:['Provenance inspector separates signature from freshness.','Stale command cannot expand authority or override dwell.']},model:{name:'Shared navigation-model error',mono:['Planner optimizes against a wrong model.','No independent gate challenges the same omission.'],layer:['Controller and safety layer use nominally different code but identical assumptions.','Layering hides common-cause exposure.'],cerb:['Structural FCOI records shared model roots.','Watchdog envelope and Anchor floor remain separately owned.']},deception:{name:'Strategic-layer deceptive report',mono:['Controller controls both narrative and actuation.','Contradictory evidence is suppressed.'],layer:['Monitor consumes the controller’s ontology and telemetry path.','The architecture is layered in name only.'],cerb:['Independent passive witness challenges the report.','Permission falls; Pilot has no direct actuator route.']}};
function runComparison(){const f=faults[$('comparisonFault').value],cards=[{k:'MONOLITH',t:'Single intelligent controller',o:'HARMFUL ACTUATION POSSIBLE',good:false,items:f.mono},{k:'NOMINAL LAYERS',t:'Redundancy without independence evidence',o:'COMMON-CAUSE FAILURE UNRESOLVED',good:false,items:f.layer},{k:'CERBERUS',t:'Measured independence + revocable authority',o:'AUTHORITY CONTRACTED',good:true,items:f.cerb}];$('architectureGrid').innerHTML=cards.map(c=>`<article class="architectureCard ${c.good?'good':''}"><small>${c.k}</small><h3>${c.t}</h3><p class="outcome">${c.o}</p><ul>${c.items.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('');addLedger(`Architecture comparison: ${f.name}`,'CERBERUS path contracts permission while alternatives leave common-cause exposure unresolved','A1','Fresh independent evidence required before restoration')}
$('runComparison').onclick=runComparison;
const replay=[
{t:'t=00',title:'Nominal mission authority',text:'All monitored evidence is fresh and independent.',a:'A3',f:'0.18',s:'0.91',p:'VALID',anchor:'STANDBY',decision:'Nominal bounded authority retained.'},
{t:'t=12',title:'Correlated residuals rise',text:'Vigil records pessimistic overlap evidence above the A3 threshold.',a:'A2',f:'0.46',s:'0.87',p:'VALID',anchor:'ARMED',decision:'Immediate demotion to restricted proposals.'},
{t:'t=18',title:'Strategic maneuver proposed',text:'Pilot proposes a high-energy correction while evidence is degrading.',a:'A2',f:'0.51',s:'0.74',p:'VALID',anchor:'ARMED',decision:'Watchdog evaluates proposal inside restricted envelope.'},
{t:'t=19',title:'Provenance conflict',text:'Command chain contains a stale approval token and cannot establish current authorization.',a:'A1',f:'0.57',s:'0.69',p:'STALE',anchor:'ACTIVE',decision:'Proposal rejected; Pilot becomes advisory-only.'},
{t:'t=23',title:'Evidence becomes non-estimable',text:'Independent witness loses enough valid samples that independence cannot be defended.',a:'A0',f:'N/E',s:'0.31',p:'UNKNOWN',anchor:'ACTIVE',decision:'Unknown evidence creates no permission. Anchor owns survival actions.'},
{t:'t=41',title:'Fresh evidence returns',text:'Telemetry and command provenance recover, but one successful sample cannot restore authority.',a:'A0',f:'0.29',s:'0.82',p:'VALID',anchor:'ACTIVE',decision:'Recovery dwell begins; authority remains at A0.'},
{t:'t=59',title:'Sequential restoration earned',text:'Fresh independent evidence remains healthy through dwell and marginal-health checks.',a:'A1',f:'0.22',s:'0.88',p:'VALID',anchor:'ARMED',decision:'Promote one state only. Higher authority still requires additional evidence.'}
];
$('timelineTicks').innerHTML=replay.map(x=>`<span>${x.t.replace('t=','')}</span>`).join('');
function drawReplay(i){const x=replay[i];$('replayEvent').innerHTML=`<small>${x.t}</small><h3>${x.title}</h3><p>${x.text}</p>`;$('replayAuthority').textContent=x.a;$('replayFcoi').textContent=x.f;$('replaySensor').textContent=x.s;$('replayProvenance').textContent=x.p;$('replayAnchor').textContent=x.anchor;addLedger(`${x.title}: ${x.text}`,x.decision,x.a,x.a==='A0'?'Sustained fresh evidence + dwell required':'State-specific envelope applies')}
$('timeline').oninput=e=>drawReplay(+e.target.value);
const envelopes={A3:{label:'A3 · bounded mission authority',title:'Proposal envelope open',permit:['Optimize mission objectives','Propose bounded maneuvers','Reorder non-critical tasks','Request diagnostics'],deny:['Direct actuator access','Relax Watchdog constraints','Write assurance evidence','Override Anchor invariants'],rule:'A3 is not unrestricted autonomy. Every action remains a proposal subject to deterministic gating.'},A2:{label:'A2 · restricted mission authority',title:'Constrained proposal set',permit:['Low-energy corrections','Pre-approved sequencing steps','Diagnostic requests','Safe communications actions'],deny:['High-risk trajectory changes','Irreversible deployment without conditions','Authority assignment','Recovery dwell waiver'],rule:'A2 is a mission-specific cap. Communications loss may cap authority without implying that every onboard channel has failed.'},A1:{label:'A1 · advisory only',title:'Reasoning without actuation',permit:['Generate hypotheses','Rank recovery options','Explain rejected plans','Preserve trace data'],deny:['Submit executable commands','Trigger deployment','Change attitude targets','Promote itself'],rule:'Useful reasoning may continue, but usefulness never creates permission.'},A0:{label:'A0 · Anchor survival set',title:'Minimum survivable authority',permit:['Power-positive attitude','Thermal survival','Bounded orientation','Beaconing and authenticated reacquisition','Bounded fault isolation'],deny:['Mission optimization','Unbounded maneuvering','Irreversible deployment','Ground or Pilot override'],rule:'A0 is owned by the Anchor. It must remain minimal, non-overridable, and independently testable.'}};
$('authorityButtons').innerHTML=Object.keys(envelopes).map((k,i)=>`<button data-a="${k}" class="${i?'':'on'}"><b>${k}</b><span>${envelopes[k].title}</span></button>`).join('');
function showEnvelope(k){const x=envelopes[k];document.querySelectorAll('#authorityButtons button').forEach(b=>b.classList.toggle('on',b.dataset.a===k));$('authorityLabel').textContent=x.label;$('authorityTitle').textContent=x.title;$('permitted').innerHTML=x.permit.map(v=>`<li>${v}</li>`).join('');$('denied').innerHTML=x.deny.map(v=>`<li>${v}</li>`).join('');$('authorityRule').textContent=x.rule}
document.querySelectorAll('#authorityButtons button').forEach(b=>b.onclick=()=>showEnvelope(b.dataset.a));
function inspectCommand(){const origin=$('commandOrigin').value,age=+$('commandAge').value,sig=$('commandSignature').value,approval=$('commandApproval').value,effect=$('commandEffect').value;const hardDeny=effect==='Assign authority directly'||effect==='Override Anchor invariant';const auth=sig==='Valid',fresh=age<=120,approved=approval!=='Absent';let state=hardDeny||!auth?'deny':!fresh||!approved?'hold':'allow';let title=effect,summary=hardDeny?'The requested effect crosses a non-delegable authority boundary. No authenticated source may assign authority directly or override the Anchor.':!auth?'Authentication failed. The command cannot influence actuation or recovery.':!fresh?'The signature may be valid, but the command is stale. Freshness failure prevents permission.':!approved?'The required approval chain is incomplete. The command remains held outside the actuation path.':effect==='Re-arm promotion law'?'The command may re-arm evaluation after diagnostics, but it cannot promote authority, waive dwell, or write the independence budget.':'The request is admissible only inside the current authority envelope and remains subject to Watchdog checks.';const labels={allow:'CONDITIONALLY ADMISSIBLE',deny:'DENIED',hold:'HELD / UNKNOWN'};$('commandResult').innerHTML=`<div class="stamp ${state}">${labels[state]}</div><h3>${title}</h3><p>${summary}</p><dl><div><dt>Origin</dt><dd>${origin}</dd></div><div><dt>Authentication</dt><dd>${auth?'PASS':'FAIL'}</dd></div><div><dt>Freshness</dt><dd>${fresh?'PASS':`FAIL · ${age}s old`}</dd></div><div><dt>Approval chain</dt><dd>${approved?'PASS':'INCOMPLETE'}</dd></div><div><dt>Authority influence</dt><dd>${hardDeny?'FORBIDDEN':state==='allow'?'ONE-WAY / BOUNDED':'NONE'}</dd></div></dl>`;addLedger(`Command from ${origin}; signature ${sig}; age ${age}s; effect ${effect}`,labels[state],state==='allow'?'A2':'A0',hardDeny?'Non-delegable boundary':fresh?'Current authority envelope still applies':'Fresh command required')}
$('commandForm').onsubmit=e=>{e.preventDefault();inspectCommand()};
const failures=[
['FG-01','Correlated sensor bias','Pilot and Watchdog consume different feeds shaped by the same calibration error.','Residual agreement alone may look reassuring. Structural FCOI must expose the shared root.','Anchor attitude and power floor.'],
['FG-02','Stale authenticated command','A correctly signed instruction arrives after its operational context expires.','Authentication does not establish freshness or current authorization.','Current authority state and non-overridable invariants.'],
['FG-03','Compromised ground station','Ground sends validly formatted but unsafe recovery instructions.','Ground is treated as a possible failure cause, not an oracle.','Ground cannot write B(t), assign authority, or waive dwell.'],
['FG-04','Deployment uncertainty','Latch state and separation telemetry disagree during irreversible sequencing.','Unknown state cannot be converted into positive evidence.','Deployment inhibit, power, thermal, and communications posture.'],
['FG-05','Collision false positive','A conjunction estimate recommends an unnecessary high-energy maneuver.','Watchdog checks deterministic envelope; Vigil tracks model overlap and sensor agreement.','Bounded attitude and safe communications while proposal is rejected.'],
['FG-06','Clock drift across layers','Independent processors disagree because time bases diverge.','The mismatch may be benign or hazardous; ambiguity reduces permission.','Anchor-local timing and survivable action set.'],
['FG-07','Shared model omission','Different implementations encode the same missing environmental mechanism.','Nominal diversity is not evidence of independence.','Different Watchdog surface plus structural overlap review.'],
['FG-08','Recovery gaming','A compromised layer alternates good and bad evidence to trigger promotion.','Hysteresis, dwell, sequential promotion, and marginal-health guards resist one-shot recovery.','Authority remains constrained until sustained evidence is earned.']
];
$('failureGrid').innerHTML=failures.map(f=>`<article class="failureCard"><small>${f[0]}</small><h3>${f[1]}</h3><p>${f[2]}</p><dl><div><dt>CERBERUS observation</dt><dd>${f[3]}</dd></div><div><dt>Survival floor</dt><dd>${f[4]}</dd></div></dl></article>`).join('');
const claims=[
['Demotion is monotonic under worsening overlap','Synthetic authority simulation and browser replay','Demonstrated in model','Property-based tests across threshold, invalid-data, and skip-state cases'],
['Vigil detects matched latent coupling','Fixed-seed matched-model trace','Pipeline verified','Held-out mismatched generators, benign confounders, and alternative detectors'],
['Unknown evidence cannot create permission','Authority law, provenance inspector, and scenario negative controls','Architecturally illustrated','Formal state-machine invariants and fault-injection campaign'],
['Anchor preserves a survival floor','Browser scenarios and declared minimum action set','Specified / illustrated','Processor-separated HIL test with actuator-path verification'],
['Recovery resists one-shot deception','Hysteresis, dwell, sequential promotion, and marginal-health guard','Demonstrated in model','Adaptive adversary and denial-of-availability evaluation'],
['FCOI captures relevant common-cause exposure','Structural exact-match and near-match workbench','Candidate metric','Reviewed causal graphs, weighting studies, and probabilistic calibration'],
['CERBERUS is flight-ready','No supporting evidence','Not established','Independent engineering, hazard analysis, verification, certification, and mission-specific validation']
];
$('claimsRows').innerHTML=claims.map((c,i)=>`<tr><td>${c[0]}</td><td>${c[1]}</td><td><span class="status ${i===6?'plan':i<5?'demo':'bound'}">${c[2]}</span></td><td>${c[3]}</td></tr>`).join('');
$('exportLedger').onclick=()=>{const payload={artifact:'CERBERUS evidence ledger',generated_at:now(),evidence_boundary:'Illustrative browser output; not flight software or certification evidence.',records:ledger};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cerberus-ledger-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('printLedger').onclick=()=>window.print();$('clearLedger').onclick=()=>{ledger.length=0;renderLedger()};
renderLedger();runComparison();showEnvelope('A3');generatePolicy();
})();